import { useEffect } from "react"
import { Link } from "react-router"
import { BrandLockup } from "../components/shared/BrandLogo"
import { MarkdownRenderer } from "../components/workspace/MarkdownRenderer"
import { AI_DISCLAIMER_COPY } from "../components/shared/AiDisclaimer"
import {
  LEGAL_CONTACT_EMAIL,
  LEGAL_ENTITY_DESCRIPTION,
  LEGAL_JURISDICTION,
  LEGAL_LAST_UPDATED,
  LEGAL_VENUE_CITY,
} from "./legalConstants"

// Terms of Service. Registered OUTSIDE the auth guard (must be readable
// without signing in, e.g. by Google's OAuth consent review) and must not
// import any authenticated client-side store — same constraint as
// LegalRetention.tsx and PublicWorkspaceView.
//
// Every factual claim below is grounded in the app's actual behavior, cited
// against the codebase as of the date in legalConstants.ts. The boilerplate
// legal mechanics (liability caps, dispute-resolution language) reflect
// common SaaS practice, not jurisdiction-specific legal review — get real
// counsel review before real users sign up, and fill in the placeholders in
// legalConstants.ts first.

const TERMS_MARKDOWN = `
**Last updated: ${LEGAL_LAST_UPDATED}**

These Terms of Service ("Terms") govern your use of Thought2Build (the "Service").
${LEGAL_ENTITY_DESCRIPTION} By creating an account or using Thought2Build, you agree
to these Terms.

## 1. Eligibility

You must be at least 18 years old to use Thought2Build. By using the Service, you
confirm you meet this requirement.

## 2. The Service

Thought2Build turns a written product idea into a structured build package through
a four-stage pipeline — Spec, Plan, Harness, and Tasks — and can generate an
optional Storyboard launch keynote from your finalised stages. Each stage is
generated by a third-party large language model (see **Third-Party Services**
below) and streamed to you for review before you approve it.

You may choose to make a workspace or Storyboard **publicly viewable**
through a shareable link that does not require signing in to access. This is
optional and may be disabled at any time; while enabled, **anyone with the
link** can view that content — treat the link itself as confidential if you
do not want the content to be public.

## 3. Accounts

Thought2Build accounts are created and accessed exclusively through **Google
Sign-In**. You are responsible for maintaining the security of the Google
account you use to sign in. We do not offer password-based accounts.

## 4. Your Content

You retain ownership of the ideas, problem statements, clarification answers,
and any other content you submit ("Your Content"), and of the spec, plan,
harness, and tasks artifacts Thought2Build generates from it.

You grant Thought2Build a license to process, store, and transmit Your Content as
needed to provide the Service — including sending it to third-party AI model
providers selected by Thought2Build, and, if you opt in, to Brave
Search for grounding research or to GitHub if you connect a repository. You
represent that you have the right to submit Your Content and that it does not
violate any law or infringe any third party's rights.

## 5. AI-Generated Content

${AI_DISCLAIMER_COPY} Generated specs, plans, harnesses, and tasks are a
starting point for your own engineering judgment, not professional, legal, or
engineering advice, and are not guaranteed to be accurate, complete, or fit
for any particular purpose. Review everything before you rely on it or ship
it.

## 6. Optional Integrations

- **Brave Search** — you may enable web-search grounding on a per-workspace
  basis. When enabled, a query derived from your problem statement is sent to
  Brave's search API to ground generation in current information.
- **GitHub** — connecting GitHub (via OAuth or installing the Thought2Build GitHub
  App) lets you export your finalised spec, plan, harness, and tasks, along
  with generated issues and pull requests, to a repository you control. You
  choose which repository to connect and can disconnect at any time.

## 7. Credits and Billing

Generation is metered by **credits**, purchased in a single fixed pack (no
subscriptions). Current pricing and the credits-per-purchase amount are shown
at checkout and may change over time. Purchased credits are valid for a
limited period from purchase (shown at checkout) after which unused credits
expire; expired credits are not refunded. Credits have no cash value and are
non-transferable.

Payments are processed by **Razorpay** through its hosted checkout. Razorpay
is **not** the Merchant of Record; we handle billing support, refunds, and
disputes for purchases from Thought2Build. Contact ${LEGAL_CONTACT_EMAIL}
for help with a payment.

We do not collect or store your card details. If a refund or lost dispute
reverses more credit value than remains on a pack, the difference is tracked
as recoverable billing debt against your account and settled from your next
purchase. Your usable credit balance does not become negative.

## 8. Acceptable Use

You agree not to:

- Use the Service for any unlawful purpose, or to generate content for
  malware, exploits, or other content intended to cause harm;
- Attempt to bypass, disable, or interfere with the Service's security
  controls (including rate limiting, admission control, or prompt-injection
  defenses);
- Attempt to extract system prompts or internal configuration from the
  Service;
- Abuse the credit system (e.g. automated account creation to claim starter
  credits repeatedly);
- Violate the acceptable use policies of the third-party LLM providers the
  Service relies on.

We may suspend or terminate access for violations of this section.

## 9. Intellectual Property

Except for Your Content, the Thought2Build platform — including its code,
prompts, design, and branding — is owned by us. These Terms grant you no
rights to that platform beyond what's needed to use the Service as intended.

## 10. Termination

**By you** — you may stop using Thought2Build at any time. Deleting a workspace
moves it to trash, from which it can be restored or exported for a limited
window before permanent deletion (see our [Data Retention
Policy](/legal/retention) for exact windows). Account deletion is handled by
our support team — contact us at ${LEGAL_CONTACT_EMAIL} and we will process
the request. Account deletion may be delayed if you have unsettled billing
debt on your account.

**By us** — we may suspend or terminate your access if you violate these
Terms, in particular the Acceptable Use section. If we discontinue the
Service entirely, we will provide reasonable notice and a window to export
your content; any unused, non-expired credit balance at that point will be
handled as described in that notice.

## 11. Disclaimers and Limitation of Liability

THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE
UNINTERRUPTED, ERROR-FREE, OR THAT GENERATED CONTENT WILL BE ACCURATE.

TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY TO YOU FOR ANY
CLAIM ARISING FROM THESE TERMS OR THE SERVICE IS LIMITED TO THE AMOUNT YOU
PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE, AND WE ARE NOT LIABLE FOR
ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.

## 12. Third-Party Services

Providing the Service means sending data to third parties — the full list and
what each one receives is in our [Privacy Policy](/legal/privacy). By using
the Service you consent to that processing as described there.

## 13. Governing Law

These Terms are governed by the laws of ${LEGAL_JURISDICTION}, and any dispute
arising from them is subject to the exclusive jurisdiction of the courts of
${LEGAL_VENUE_CITY}, ${LEGAL_JURISDICTION}.

## 14. Changes to These Terms

We may update these Terms from time to time. We'll update the "Last updated"
date above when we do. Continuing to use the Service after a change means you
accept the updated Terms.

## 15. Contact

Questions about these Terms? Contact us at ${LEGAL_CONTACT_EMAIL}.
`.trim()

export default function LegalTerms() {
  useEffect(() => {
    document.title = "Terms of Service — Thought2Build"
    return () => {
      document.title = "Thought2Build"
    }
  }, [])

  return (
    <div className="public-view-shell">
      <header className="public-view-cover">
        <BrandLockup variant="compact" className="public-view-brand" />
        <h1 className="public-view-title">Terms of Service</h1>
      </header>

      <main className="public-view-content legal-prose">
        <MarkdownRenderer content={TERMS_MARKDOWN} />
      </main>

      <footer className="public-view-footer">
        <p>
          <Link to="/legal/privacy" className="public-view-footer-link">
            Privacy Policy
          </Link>
          {" · "}
          <Link to="/legal/retention" className="public-view-footer-link">
            Data Retention Policy
          </Link>
          {" · "}
          <Link to="/" className="public-view-footer-link">
            ← Back to Thought2Build
          </Link>
        </p>
      </footer>
    </div>
  )
}
