"""Deterministic parser that extracts T-NNN tasks from TASKS.md.

Takes a string, returns a list. Fully testable with inline fixtures.

Two issue-body shapes are produced per task:

- ``body_md`` — the Phase-13 body: the title heading, the raw task subsections
  preserved verbatim, and a Thought2Build footer.
- ``agent_body_md`` — the Phase-21 (T-277) **agent-ready** body: a machine-
  readable YAML front-matter header (``task_ref``, ``stage``, ``spec_anchors``,
  ``test_path``) followed by five fixed sections — **Context**, **Acceptance
  criteria**, **Files**, **The test that must pass**, **Spec links** — so a
  coding agent can pick the issue up and open a PR with no extra context
  fetching. The free-text fields lifted from the (LLM-generated, untrusted)
  TASKS.md are sanitised with the same policy as public share / PDF.

Spec anchors reuse ``artifact_validator.SECTION_CONTRACTS`` headings so a link
stays stable across refinement (it slugs a canonical section heading, not a
volatile body offset). Matching/dedup is always on the content-derived
``compute_task_ref`` (T-266), never the human ``T-NNN`` number.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field

from services.pipeline.artifact_validator import SECTION_CONTRACTS
from services.security.sanitizer import sanitize_text

_TASK_HEADING = re.compile(r"^###\s+(T-\d+):\s+(.+?)\s*$", re.MULTILINE)
_FOOTER = "*Generated by [Thought2Build](https://thought2build.com)*"

# Collapse all interior whitespace runs so trivial reflowing of a title does not
# change its identity.
_WHITESPACE = re.compile(r"\s+")

# Labels every agent-ready issue carries (T-277). GitHub auto-creates a missing
# label on issue creation, so passing these is all that is needed.
AGENT_LABELS: tuple[str, ...] = ("thought2build", "stage:tasks", "ready-for-agent")

# A ``**Field:**`` line opens a labelled subsection in a generated task body.
_BOLD_FIELD = re.compile(r"^\*\*(?P<name>[^*]+?):\*\*\s*(?P<rest>.*)$")
# Backtick-quoted test references inside the **Harness refs:** field.
_BACKTICK_REF = re.compile(r"`([^`]+)`")


def normalized_task_title(title: str) -> str:
    """The case- and whitespace-folded form :func:`compute_task_ref` hashes.

    Exposed so callers that need to detect same-title collisions key on exactly
    what the ref is derived from, rather than re-deriving a near-miss
    normalisation of their own.
    """
    return _WHITESPACE.sub(" ", title).strip().casefold()


def compute_task_ref(title: str, *, stage: str = "tasks", occurrence: int = 0) -> str:
    """Return the stable, content-derived matching key for a task (spec §10,
    Assumption 23).

    This is the single dedup/identity key for an :class:`IntegrationPushTask`.
    It is **content-derived** — a short hash of the normalized task title scoped
    by ``stage`` — and deliberately does **not** depend on the human-readable
    ``T-NNN`` number. That is the load-bearing property: a refinement that
    renumbers ``T-001`` → ``T-002`` while keeping the same title yields the same
    ``task_ref``, so re-export/reconcile/increment sync update the *same* GitHub
    Issue instead of opening a duplicate. The ``T-NNN: {title}`` string remains
    the issue *title*; matching is always on this ref.

    Defined in Phase A so export (T-269), agent issues (T-277), and increments
    (T-279/T-280) all share one matching key rather than re-deriving it.

    Normalization (case- and whitespace-folded) keeps the key stable across
    cosmetic edits; the ``stage`` prefix prevents collisions between same-titled
    tasks that originate in different stages. The 48-bit hex prefix is amply
    collision-resistant across *distinct* titles in a single workspace.

    Identical titles are NOT distinct, which is what ``occurrence`` is for. Two
    tasks titled "Add unit tests" — or "Set Up CI" and "set up ci", which fold
    together — otherwise derive the same key, and the ``(push_id, task_ref)``
    unique constraint then rejects the second one mid-export. ``occurrence`` is
    that task's index among the same-normalised titles in document order, and
    **occurrence 0 is byte-identical to the unsalted form**, so every ref already
    persisted in production still matches and renumber-invariance is untouched.

    Callers should not pass ``occurrence`` by hand and should not call this in a
    loop over a task list at all: :func:`parse_tasks` resolves each task's ref
    once, in document order, and hands it back on
    :attr:`ParsedTask.task_ref`. Read that field instead — deriving a ref
    per-task from the title cannot see the sibling that shares it.
    """
    normalized = normalized_task_title(title)
    seed = f"{stage}\x1f{normalized}"
    if occurrence:
        seed = f"{seed}\x1f{occurrence}"
    digest = hashlib.sha256(seed.encode()).hexdigest()
    return f"task-{digest[:12]}"


@dataclass(frozen=True)
class ParsedTask:
    """A single task extracted from TASKS.md.

    Attributes:
        ref: The task reference, e.g. ``"T-001"``.
        title: The heading text after the ref, e.g. ``"Set up project structure"``.
        body_md: The Phase-13 GitHub Issue body — title heading + raw task body +
            Thought2Build footer. Retained verbatim for backward compatibility.
        agent_body_md: The Phase-21 (T-277) agent-ready body — YAML header + the
            five fixed sections. This is what the v2 export hands to
            ``create_issue``.
        labels: The labels the agent-ready issue carries (:data:`AGENT_LABELS`).
        raw_body: The task's source body between its heading and the next ``###``,
            preserved verbatim. Increment generation (T-279) re-appends this under
            a renumbered heading when it grows TASKS.md, so the appended section
            matches the source document's shape exactly.
        task_ref: The stable matching identity for this task, resolved ONCE at
            parse time by :func:`parse_tasks` with its document-order
            occurrence already applied. Every consumer — export, increment sync,
            the ``Closes #N`` map, the Projects board, the sync panel — must read
            this field rather than re-deriving it, because a per-task
            ``compute_task_ref(title)`` cannot see the sibling that shares the
            title and would collapse the two onto one key.
    """

    ref: str
    title: str
    body_md: str
    agent_body_md: str = ""
    labels: tuple[str, ...] = field(default_factory=tuple)
    raw_body: str = ""
    task_ref: str = ""


def parse_tasks(content: str) -> list[ParsedTask]:
    """Extract every ``### T-NNN: <title>`` task from TASKS.md content.

    Returns tasks in document order. Empty input or input with no T-NNN
    headings returns an empty list.

    The body for each task is everything between its heading and the next
    ``###`` heading (or end of document), stripped of leading and trailing
    whitespace. Headings of any other depth (``##``, ``####``, ``#####``)
    inside a task body are preserved verbatim — only sibling ``###``
    headings act as task delimiters.
    """
    if not content:
        return []

    matches = list(_TASK_HEADING.finditer(content))
    if not matches:
        return []

    tasks: list[ParsedTask] = []
    occurrences: dict[str, int] = {}
    for index, match in enumerate(matches):
        ref = match.group(1)
        title = match.group(2).strip()

        body_start = match.end()
        body_end = (
            matches[index + 1].start() if index + 1 < len(matches) else len(content)
        )
        raw_body = content[body_start:body_end].strip()

        # Occurrence among same-normalised titles, in document order. Only a
        # repeat is salted, so a document with unique titles (the overwhelming
        # majority) produces byte-identical refs and issue bodies to before.
        normalized = normalized_task_title(title)
        occurrence = occurrences.get(normalized, 0)
        occurrences[normalized] = occurrence + 1
        task_ref = compute_task_ref(title, occurrence=occurrence)

        body_md = _format_issue_body(title=title, raw_body=raw_body)
        agent_body_md = _format_agent_issue_body(
            title=title, raw_body=raw_body, task_ref=task_ref
        )
        tasks.append(
            ParsedTask(
                ref=ref,
                title=title,
                body_md=body_md,
                agent_body_md=agent_body_md,
                labels=AGENT_LABELS,
                raw_body=raw_body,
                task_ref=task_ref,
            )
        )

    return tasks


def _format_issue_body(*, title: str, raw_body: str) -> str:
    """Render a GitHub Issue body for the task.

    The format mirrors the source TASKS.md: ``## {title}`` heading, the
    raw subsections preserved verbatim, a horizontal rule, and a Thought2Build
    footer. Two trailing newlines keep the footer separated when the
    issue is pasted into other markdown contexts.
    """
    sections: list[str] = [f"## {title}"]
    if raw_body:
        sections.append(raw_body)
    sections.append("---")
    sections.append(_FOOTER)
    return "\n\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Agent-ready issue body (T-277)
# ---------------------------------------------------------------------------

# Source field names (lower-cased) mapped onto each fixed agent section. The
# first present source wins; absent sources fall back to a useful default so
# every one of the five sections always renders.
_CONTEXT_FIELDS = ("context", "description", "summary", "overview", "goal")
_ACCEPTANCE_FIELDS = ("acceptance criteria", "acceptance", "definition of done")
_FILES_FIELDS = (
    "files",
    "affected modules/files",
    "affected files",
    "affected modules",
    "affected",
)
_TEST_FIELDS = ("harness refs", "test that must pass", "tests", "test")


def _format_agent_issue_body(
    *, title: str, raw_body: str, task_ref: str | None = None
) -> str:
    """Render the agent-ready GitHub Issue body (T-277).

    A machine-readable YAML header (``task_ref``/``stage``/``spec_anchors``/
    ``test_path``) followed by the five fixed sections. Free text lifted from the
    untrusted TASKS.md is sanitised; the structure is generated, so it is safe.
    """
    fields = _extract_bold_fields(raw_body)
    lead = _leading_prose(raw_body)

    context = (
        _first_field(fields, _CONTEXT_FIELDS)
        or lead
        or (
            "Implement this task so its harness test(s) pass. See the linked spec "
            "sections for the full requirement."
        )
    )
    acceptance = _first_field(fields, _ACCEPTANCE_FIELDS) or (
        "The task's harness test(s) listed below pass, and the change matches the "
        "linked spec sections."
    )
    files = _first_field(fields, _FILES_FIELDS) or (
        "Touch the files implied by the test path below and the repository layout."
    )

    test_refs = _extract_test_refs(fields)
    # Resolved by the caller (parse_tasks) so a same-titled sibling's salt is
    # reflected in the YAML header too; falls back for direct callers.
    task_ref = task_ref or compute_task_ref(title)
    anchors = _spec_anchors(f"{title}\n{raw_body}")

    header = _yaml_header(
        task_ref=task_ref,
        spec_anchors=anchors,
        test_path=test_refs,
    )

    test_block = (
        "\n".join(f"- `{_san(ref)}`" for ref in test_refs)
        if test_refs
        else "No harness test is referenced yet — add one under `harness/` that "
        "pins this task's behaviour, then make it pass."
    )
    spec_block = "\n".join(f"- [`{a}`]({a})" for a in anchors)

    body = (
        f"{header}\n"
        f"# {_san(title)}\n\n"
        f"## Context\n{_san(context)}\n\n"
        f"## Acceptance criteria\n{_san(acceptance)}\n\n"
        f"## Files\n{_san(files)}\n\n"
        f"## The test that must pass\n{test_block}\n\n"
        f"## Spec links\n{spec_block}\n\n"
        f"---\n{_FOOTER}\n"
    )
    return body


def _yaml_header(
    *, task_ref: str, spec_anchors: list[str], test_path: list[str]
) -> str:
    """Deterministic YAML front-matter carrying the machine-readable keys."""
    lines = ["---", f"task_ref: {task_ref}", "stage: tasks"]
    lines.append("spec_anchors:")
    for anchor in spec_anchors:
        lines.append(f"  - {anchor}")
    lines.append("test_path:")
    for ref in test_path:
        lines.append(f"  - {_yaml_scalar(_san(ref))}")
    lines.append(f"labels: [{', '.join(AGENT_LABELS)}]")
    lines.append("---")
    return "\n".join(lines) + "\n"


def _yaml_scalar(value: str) -> str:
    """Quote a YAML scalar when it could otherwise be mis-parsed."""
    if value == "" or re.search(r"[:#\[\]{}]", value):
        return '"' + value.replace('"', "'") + '"'
    return value


def _extract_bold_fields(raw_body: str) -> dict[str, str]:
    """Map ``**Field:**`` subsection name (lower-cased) → its text value.

    A field's value runs from its line until the next ``**Field:**`` or any
    ``#`` heading. The first occurrence of a name wins.
    """
    fields: dict[str, str] = {}
    current: str | None = None
    buffer: list[str] = []

    def flush() -> None:
        if current is not None and current not in fields:
            fields[current] = "\n".join(buffer).strip()

    for line in raw_body.split("\n"):
        match = _BOLD_FIELD.match(line.strip())
        if match:
            flush()
            current = match.group("name").strip().lower()
            buffer = [match.group("rest").strip()]
        elif line.lstrip().startswith("#"):
            flush()
            current = None
            buffer = []
        elif current is not None:
            buffer.append(line)
    flush()
    return fields


def _leading_prose(raw_body: str) -> str:
    """The body text before the first ``**Field:**`` or ``#`` heading."""
    lines: list[str] = []
    for line in raw_body.split("\n"):
        stripped = line.strip()
        if _BOLD_FIELD.match(stripped) or stripped.startswith("#"):
            break
        lines.append(line)
    return "\n".join(lines).strip()


def _first_field(fields: dict[str, str], names: tuple[str, ...]) -> str | None:
    for name in names:
        value = fields.get(name)
        if value:
            return value
    return None


def _extract_test_refs(fields: dict[str, str]) -> list[str]:
    """Backtick-quoted test references from the ``Harness refs``/test field.

    Order-preserving and de-duplicated so the header is deterministic.
    """
    for name in _TEST_FIELDS:
        text = fields.get(name)
        if text:
            seen: list[str] = []
            for ref in _BACKTICK_REF.findall(text):
                cleaned = ref.strip()
                if cleaned and cleaned not in seen:
                    seen.append(cleaned)
            if seen:
                return seen
    return []


def _spec_anchors(text: str) -> list[str]:
    """Stable spec/plan anchors derived from ``SECTION_CONTRACTS`` headings.

    Reuses the canonical section headings (artifact_validator) so an anchor
    survives refinement: it slugs a fixed heading, not a volatile body offset.
    Emits an anchor for each canonical heading the task text references, in
    ``SECTION_CONTRACTS`` order (deterministic); falls back to the doc roots when
    a task references none explicitly.
    """
    haystack = text.lower()
    anchors: list[str] = []
    for stage, filename in (("spec", "SPEC.md"), ("plan", "PLAN.md")):
        for heading in SECTION_CONTRACTS.get(stage, []):
            label = heading.lstrip("# ").strip()
            if label.lower() in haystack:
                anchors.append(f"{filename}#{_slugify(label)}")
    return anchors or ["SPEC.md", "PLAN.md"]


def _slugify(heading: str) -> str:
    """GitHub-style heading anchor: lowercase, spaces→-, punctuation dropped."""
    slug = heading.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug)
    return slug.strip("-")


def _san(text: str) -> str:
    """Sanitise untrusted free text (same policy as public share / PDF)."""
    return sanitize_text(text).strip()
